//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Functional.Domain.Entities.Validations.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Functional.Domain.Entities.Validations.Common.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caso de uso deve possuir um código.
        /// </summary>
        public static string CasoDeUsoErroCasoDeUsoDevePossuirUmCodigo {
            get {
                return ResourceManager.GetString("CasoDeUsoErroCasoDeUsoDevePossuirUmCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caso de uso deve possuir um fluxo principal válido.
        /// </summary>
        public static string CasoDeUsoErroCasoDeUsoDevePossuirUmFluxoPrincipalValido {
            get {
                return ResourceManager.GetString("CasoDeUsoErroCasoDeUsoDevePossuirUmFluxoPrincipalValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caso de uso deve possuir um título.
        /// </summary>
        public static string CasoDeUsoErroCasoDeUsoDevePossuirUmTitulo {
            get {
                return ResourceManager.GetString("CasoDeUsoErroCasoDeUsoDevePossuirUmTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Projeto está vazio, ou mal formatado.
        /// </summary>
        public static string ErroCodigoDeProjetoMalFormatado {
            get {
                return ResourceManager.GetString("ErroCodigoDeProjetoMalFormatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um Projeto precisa possuir um nome.
        /// </summary>
        public static string ErroProjetoPrecisaTerUmNome {
            get {
                return ResourceManager.GetString("ErroProjetoPrecisaTerUmNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fluxo deve possuir passos.
        /// </summary>
        public static string FluxoErroFluxoDevePossuirPassos {
            get {
                return ResourceManager.GetString("FluxoErroFluxoDevePossuirPassos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O fluxo deve possuir um título.
        /// </summary>
        public static string FluxoErroFluxoDevePossuirUmTitulo {
            get {
                return ResourceManager.GetString("FluxoErroFluxoDevePossuirUmTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O passo deve possuir uma descrição.
        /// </summary>
        public static string PassoErroPassoDevePossuirDescricao {
            get {
                return ResourceManager.GetString("PassoErroPassoDevePossuirDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O passo deve possuir uma sequencia válida.
        /// </summary>
        public static string PassoErroPassoDevePossuirSequencia {
            get {
                return ResourceManager.GetString("PassoErroPassoDevePossuirSequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O requisito deve pertencer a um projeto valido.
        /// </summary>
        public static string RequisitoDevePertencerAUmProjetoValido {
            get {
                return ResourceManager.GetString("RequisitoDevePertencerAUmProjetoValido", resourceCulture);
            }
        }
    }
}
