namespace Functional.Domain.Interfaces.Service
{
    using System;

    using Functional.Domain.Entities.Model;
    using Functional.Domain.Interfaces.Service.Common;
    public interface IRequisitoService : IService<Requisito>
    {
        /// <summary>
        /// Dado um projeto, recupera o próximo código de requisito para o projeto
        /// </summary>
        /// <param name="projeto">projeto a que pertence o requisito</param>
        /// <returns>Uma string</returns>
        /// <autogeneratedoc />
        string GetProximoCodigo(Projeto projeto);
    }
}
