namespace Functional.Mvc.Helpers.ResultsExtensions
{
    using System.Web.Mvc;
    using System.Web.Script.Serialization;

    /// <summary>
    /// Retorna um resultado em Json para o callback do modal
    /// </summary>
    internal sealed class JsonDialogActionResult : ModalActionResult
    {
        public JsonDialogActionResult(string message, object jsonDialogResult)
            : base(message, jsonDialogResult)
        {
        }

        public JsonDialogActionResult(string message)
            : base(message)
        {
        }

        /// <summary>
        /// Processa o retorno dos dados para o callback do modal
        /// </summary>
        /// <param name="context">O contexto</param>
        /// <autogeneratedoc />
        protected override void ProcessData(ControllerContext context)
        {
            var serializer = new JavaScriptSerializer();
            this.ParsedData = serializer.Serialize(this.CallbackData);
        }
    }
}